version: "3.5"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["sh", "build.sh"]
    tty: true
    links:
      - db
    volumes:
      - ./backend/:/backend/
    ports:
      - 8080:8080
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./client/Dockerfile
    tty: true
    volumes:
      - ./client/:/app/
      - /app/node_modules
    command: ["sh", "production-build.sh"]
    ports:
      - "3000:3000"
  db:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - ./db/:/private/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - PGPASSWORD=pg
      - POSTGRES_DB=pg
      - DATABASE_HOST=db
