version: "3.5"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/backend/
    command: ["sh", "build.sh"]
    tty: true
    restart: always
    ports:
      - 3000:8080