version: "3.5"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["sh", "build.sh"]
    tty: true
    restart: always
    links:
      - db
    ports:
      - 8080:8080
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./client/Dockerfile
    restart: always
    tty: true
    depends_on:
      - backend
    command: npm run dev
    ports:
      - "3000:3000"