version: "3.5"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/backend/
    command: ["sh", "build.sh"]
    tty: true
    restart: always
    ports:
      - 8080:8080
  # frontend:
  #   container_name: frontend
  #   volumes:
  #     - ./client/:/app/
  #     - /app/node_modules
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   restart: always
  #   tty: true
  #   depends_on:
  #     - backend
  #   command: npm run dev
  #   ports:
  #     - "3000:3000"